#!/usr/bin/env python

import sys
import struct


def unpack_advance(fmt, buffer, offset):
    """Unpack a string from a buffer. Return the unpacked values and the
    new offset.
    """
    res = struct.unpack_from(fmt, buffer, offset)
    return res, offset + struct.calcsize(fmt)


def disttest(infile):
    # Parse the packed input format.
    buffer = infile.read()
    offset = 0
    while offset < len(buffer):
        (length,), offset = unpack_advance('i', buffer, offset)
        row, offset = unpack_advance('%sf' % length, buffer, offset)
        print(row)


if __name__ == '__main__':
    disttest(sys.stdin)
