#!/usr/bin/env python

import sys
import struct
import random


def distgen(count, kind, dimension, args, outf=sys.stdout):
    for i in range(count):
        row = rowgen(kind, dimension, args)
        outf.write(struct.pack('i', len(row)))
        outf.write(struct.pack('%sf' % len(row), *row))


def rowgen(kind, dims, args):
    if kind == 'uniform':
        min, max = [float(a) for a in args]
        out = []
        for i in range(dims):
            out.append(random.uniform(min, max))
        return out

    elif kind == 'normal':
        mean, variance = [float(a) for a in args]
        out = []
        for i in range(dims):
            out.append(random.normalvariate(mean, variance))
        return out

    else:
        raise Exception('unknown distribution kind {}'.format(kind))


if __name__ == "__main__":
    distgen(int(sys.argv[1]), sys.argv[2], int(sys.argv[3]), sys.argv[4:])
